/*
 * wizardCrack.java
 *
 * Created on May 12, 2012, 4:44:23 PM
 */

package wepifier;

import javax.swing.JOptionPane;
import main.*;

/**
 *
 * @author root
 */
public class wizardCrack extends javax.swing.JDialog {

    private int currentPage = 1;

    /**
     * Creates new form wizardCrack
     */
    public wizardCrack(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        message.setText("Press next!");
        message.setEditable(false);
        message.setVisible(true);
        next.setVisible(true);
        back.setVisible(false);
        finish.setVisible(false);
        page1.setVisible(true);
        page2.setVisible(false);
        page3.setVisible(false);
        page4.setVisible(false);
      //  message.setText("Let us begin!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        page1 = new javax.swing.JPanel();
        message = new javax.swing.JTextArea();
        page2 = new javax.swing.JPanel();
        chooseBssidCombo = new javax.swing.JComboBox();
        chooseBssidLabel = new javax.swing.JLabel();
        page3 = new javax.swing.JPanel();
        typeOfAttackCombo = new javax.swing.JComboBox();
        typeOfAttackLabel = new javax.swing.JLabel();
        page4 = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Wizard Crack"); // NOI18N
        setResizable(false);
        setTitle("Wizard Crack");


        
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wepifier.WEPifierApp.class).getContext().getResourceMap(wizardCrack.class);
        next.setText(resourceMap.getString("next.text")); // NOI18N
        next.setName("next"); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setText(resourceMap.getString("back.text")); // NOI18N
        back.setActionCommand(resourceMap.getString("back.actionCommand")); // NOI18N
        back.setName("back"); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
                message.setVisible(true);
            }
        });

        page1.setBackground(resourceMap.getColor("page1.background")); // NOI18N
        page1.setForeground(resourceMap.getColor("page1.foreground")); // NOI18N
        page1.setName("page1"); // NOI18N

        message.setBackground(resourceMap.getColor("message.background")); // NOI18N
        message.setForeground(resourceMap.getColor("message.foreground")); // NOI18N
        message.setText(resourceMap.getString("message.text")); // NOI18N
        message.setName("message"); // NOI18N

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1);
        page1.setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
                page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 476, Short.MAX_VALUE).addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(page1Layout.createSequentialGroup().addGap(176, 176, 176).addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(206, Short.MAX_VALUE))));
        page1Layout.setVerticalGroup(
                page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 255, Short.MAX_VALUE).addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(page1Layout.createSequentialGroup().addGap(119, 119, 119).addComponent(message).addContainerGap(119, Short.MAX_VALUE))));

        page2.setBackground(resourceMap.getColor("page2.background")); // NOI18N
        page2.setForeground(resourceMap.getColor("page2.foreground")); // NOI18N
        page2.setName("page2"); // NOI18N

        chooseBssidCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        chooseBssidCombo.setName("chooseBssidCombo"); // NOI18N

        chooseBssidLabel.setBackground(resourceMap.getColor("chooseBssidLabel.background")); // NOI18N
        chooseBssidLabel.setForeground(resourceMap.getColor("chooseBssidLabel.foreground")); // NOI18N
        chooseBssidLabel.setText(resourceMap.getString("chooseBssidLabel.text")); // NOI18N
        chooseBssidLabel.setName("chooseBssidLabel"); // NOI18N

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2);
        page2.setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
                page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(page2Layout.createSequentialGroup().addGap(71, 71, 71).addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(chooseBssidCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(chooseBssidLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap(115, Short.MAX_VALUE)));
        page2Layout.setVerticalGroup(
                page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(page2Layout.createSequentialGroup().addGap(59, 59, 59).addComponent(chooseBssidLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(chooseBssidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(141, Short.MAX_VALUE)));

        page3.setBackground(resourceMap.getColor("page3.background")); // NOI18N
        page3.setForeground(resourceMap.getColor("page3.foreground")); // NOI18N
        page3.setName("page3"); // NOI18N


        typeOfAttackCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"ARPReplay", "Chop-Chop", "Fragmentation", "InjectionTest"}));
        typeOfAttackCombo.setName("typeOfAttackCombo"); // NOI18N

        typeOfAttackLabel.setBackground(resourceMap.getColor("typeOfAttackLabel.background")); // NOI18N
        typeOfAttackLabel.setForeground(resourceMap.getColor("typeOfAttackLabel.foreground")); // NOI18N
        typeOfAttackLabel.setText(resourceMap.getString("typeOfAttackLabel.text")); // NOI18N
        typeOfAttackLabel.setDoubleBuffered(true);
        typeOfAttackLabel.setName("typeOfAttackLabel"); // NOI18N

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
                page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page3Layout.createSequentialGroup().addContainerGap(106, Short.MAX_VALUE).addComponent(typeOfAttackLabel).addGap(198, 198, 198)).addGroup(page3Layout.createSequentialGroup().addGap(73, 73, 73).addComponent(typeOfAttackCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(117, Short.MAX_VALUE)));
        page3Layout.setVerticalGroup(
                page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(page3Layout.createSequentialGroup().addGap(58, 58, 58).addComponent(typeOfAttackLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(typeOfAttackCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(142, Short.MAX_VALUE)));

        page4.setName("page4"); // NOI18N

        javax.swing.GroupLayout page4Layout = new javax.swing.GroupLayout(page4);
        page4.setLayout(page4Layout);
        page4Layout.setHorizontalGroup(
                page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 476, Short.MAX_VALUE));
        page4Layout.setVerticalGroup(
                page4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 250, Short.MAX_VALUE));


        finish.setText(resourceMap.getString("finish.text")); // NOI18N
        finish.setName("finish"); // NOI18N
        finish.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(202, Short.MAX_VALUE).addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addComponent(page2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(page3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(page1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(page4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(page2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(next).addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(finish)).addContainerGap()).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(page3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(53, Short.MAX_VALUE))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(page1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(48, Short.MAX_VALUE))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(page4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(53, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void generatePasswdDialog()
    {
        JOptionPane.showConfirmDialog(this.getParent(),"Password: "+ wc.readPassword(chooseBssidCombo.getSelectedIndex()),
                wc.getTarget(chooseBssidCombo.getSelectedIndex()),JOptionPane.YES_OPTION ,
                   JOptionPane.PLAIN_MESSAGE , null);
    }
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (currentPage == 1) {
            wc.firstPhase();
            chooseBssidCombo.setModel(new javax.swing.DefaultComboBoxModel(wc.getTargets()));
            page1.setVisible(false);
            page2.setVisible(true);
            page3.setVisible(false);
            page4.setVisible(false);
            back.setVisible(true);
            currentPage++;
        } else if (currentPage == 2) {
           wc.secondPhase(chooseBssidCombo.getSelectedIndex());
            page1.setVisible(false);
            page2.setVisible(false);
            page3.setVisible(true);
            page4.setVisible(false);
            currentPage++;
        } else if (currentPage == 3) {
            wc.typeOfAttack(3 + typeOfAttackCombo.getSelectedIndex());
            wc.startCrack();
            wc.exportCSVData(chooseBssidCombo.getSelectedIndex());
            wc.stopMonitor();
            generatePasswdDialog();
            page1.setVisible(false);
            page2.setVisible(false);
            page3.setVisible(false);
            page4.setVisible(true);
            next.setVisible(false);
            finish.setVisible(true);
            currentPage++;
        }
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (currentPage < 2) {
            back.setVisible(false);
            finish.setVisible(false);
        } else if (currentPage == 2) {

            page1.setVisible(true);
            page2.setVisible(false);
            page3.setVisible(false);
            page4.setVisible(false);
            back.setVisible(false);
            next.setVisible(true);
            finish.setVisible(false);
            currentPage--;
        } else if (currentPage == 3) {

            page1.setVisible(false);
            page2.setVisible(true);
            page3.setVisible(false);
            page4.setVisible(false);
            next.setVisible(true);
            finish.setVisible(false);
            currentPage--;
        } else if (currentPage == 4) {

            page1.setVisible(false);
            page2.setVisible(false);
            page3.setVisible(true);
            page4.setVisible(false);
            next.setVisible(true);
            finish.setVisible(false);
            currentPage--;
        }
    }//GEN-LAST:event_backActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        this.dispose();
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                wizardCrack dialog = new wizardCrack(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private WEPConnection wc = new WEPConnection();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox chooseBssidCombo;
    private javax.swing.JLabel chooseBssidLabel;
    private javax.swing.JButton finish;
    private javax.swing.JTextArea message;
    private javax.swing.JButton next;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel page3;
    private javax.swing.JPanel page4;
    private javax.swing.JComboBox typeOfAttackCombo;
    private javax.swing.JLabel typeOfAttackLabel;
    // End of variables declaration//GEN-END:variables
    
}
