/**
 * WEPifier v1.0
 * FilterData.class
 * This class is meant to filter the data output by the aircrack-ng
 * (Still under development)
 */
package main;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FilterData {
	private String data=" "; // data read from the file
	private File f;          // file for processing
	private String[] BSSID;  // array of BSSID's
	private String[] ESSID; // array of ESSID's
	private int sec=0,index=0; // number of sections and index of array
        private String[] protection; // array of protections
        public FilterData(){}
	public FilterData(String path)
	{
		f = new File(path);

		try {
			readFile();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
	public void setData(String str){data=str;}
	public void setBSSID(String[] str){BSSID = str;}
	public void setName(String[] str){ESSID = str;}
        /**
         * Will retrieve the local folder.
         * @return The local folder where the application is running
         */
        public String getLocalFolder(){
            String str = f.getAbsolutePath();
            String folder="";
            String temp="";
            for(int i=0;i<str.length();i++)
            {
                char c = str.charAt(i);
                temp+=c;
                if(c=='/')
                {
                    folder+=temp;
                    temp="";
                }
            }
            return folder;
        }
        /**
         * Will retrieve the local folder.
         * @param f Local file for processing its folder
         * @return  The local folder where the application is running
         */
        public String getLocalFolder(File f){
            String str = f.getAbsolutePath();
            String folder="";
            String temp="";
            for(int i=0;i<str.length();i++)
            {
                char c = str.charAt(i);
                temp+=c;
                if(c=='/')
                {
                    folder+=temp;
                    temp="";
                }
            }
            return folder;
        }

	public String getData(){return data;}
        public String[] getProtection(){return protection;}
	public String[] getBSSID(){return BSSID;}
	public String[] getName(){return ESSID;}
        public int getSizeOfBssid(){return index;}
	public String getBSSIDAtIndex(int index){
		if(index<0||index>=BSSID.length)
		{
			System.err.println("IndexOutOfBounds");
			return null;
		}
		return BSSID[index];
	}
        public String getProtectionAtIndex(int index)
        {
            if(index<0||index>=protection.length)
		{
			System.err.println("IndexOutOfBounds");
			return null;
		}
            return protection[index];
        }
	public String getESSIDAtIndex(int index)
        {
            if(index<0||index>=ESSID.length)
		{
			System.err.println("IndexOutOfBounds");
			return null;
		}
            return ESSID[index];
        }
        /**
         * Searches through the array to find the given BSSID
         * @param mac BSSID given by the user for searching
         * @return Location of the BSSID in the array if found 
         */
        public int getTargetByMAC(String mac)
        {
            for(int i=0;i<BSSID.length;i++)
                if(BSSID[i].equalsIgnoreCase(mac))
                    return i;
            return -1;
        }
        /**
         * Will filter common mistakes done when entering BSSID's by hand.
         * @param mac BSSID given for filtering
         * @return Clean BSSID for processing
         */
        public static String filterMac(String mac)
        {
            mac = mac.replace("-", ":");
            if(mac.endsWith(" "))
                mac.replace(" ", "");
            return mac;
        }
        /**
         * Reads data generated by aircrack-ng suite and prepares it for
         * filtering.
         * 
         * @throws FileNotFoundException 
         */
	public void readFile() throws FileNotFoundException
	{
		Scanner scan = new Scanner(f);
		while(scan.hasNext())
		{
			data+=scan.nextLine();
			data+="\n";
			sec++;
		}
		//System.out.println(data);
		filterData();
		//testReader();
	}
	
	private void filterData()
	{
            if(sec==0) return;
		String[] temp = data.split(";");
                protection = new String[sec-1];
		BSSID = new String[sec-1];
		ESSID = new String[sec-1];
		for(int i=0;i<temp.length;i++)
		{
			if(temp[i].equalsIgnoreCase("infrastructure"))
			{
					ESSID[index]=temp[i+1];
					BSSID[index]=temp[i+2];
                                        protection[index]=temp[i+6];
					index++;
			}
		}
	}
}
